# image:  https://hub.docker.com/r/martinhelmich/typo3
# compose file: https://github.com/martin-helmich/docker-typo3/blob/master/11.5/docker-compose.yml

version: '3.8'

services:
  typo3:
    image: martinhelmich/typo3:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:80
    volumes:
      - typo3:/var/www/html
    restart: always

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-mysql
    restart: always
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    ports:
     - ${DB_MYSQL_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}

networks:
  default:
      name: ${APP_NAME}

volumes:
  typo3:
    driver: local
  mysql:
    driver: local